### ISSUE TITLE
Add more sensible JVM arguments

### ISSUE THREAD

**Issue by tqvarnst** [openshiftio/launchpad-backend#68]
Currently the CMD in the Dockerfile is set to `java -jar launchpad-backend-swarm.jar`.  Since wildfly swarm default will bind to all interfaces (including ipv6) I would recommend that we add `-Djava.net.preferIPv4Stack=true` as an argument.

Additionally, it's preferable if we set Xms and Xms values because how default memory allocation works for the JVM inside a container (see https://developers.redhat.com/blog/2017/03/14/java-inside-docker/). I've tested and verified the following settings which I recommend:

`CMD ["java", "-server", "-Xms64m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true", "-jar", "launchpad-backend-swarm.jar"]`

**Comment by quintesse** [comment]
Thanks @tqvarnst !

Btw, is there a specific reason for that `preferIPv4Stack` option? Is it somehow not advisable to have IPv6 support?

**Comment by tqvarnst** [comment]
When I was trying to run this on my mac using Docker CE and oc cluster up (which I know is not a supported platform) the backend fails to start with the following stack trace

    2017-10-16 06:56:58,548 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
      | at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
      | at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
      | at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
      | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      | at java.lang.Thread.run(Thread.java:748)
      | Caused by: java.net.SocketException: Protocol family unavailable
      | at sun.nio.ch.Net.bind0(Native Method)
      | at sun.nio.ch.Net.bind(Net.java:433)
      | at sun.nio.ch.Net.bind(Net.java:425)
      | at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
      | at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
      | at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:171)
      | at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:245)
      | at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
      | at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
      | ... 5 more`

I believe that is connected to the fact that my mac default has IPv6 enabled, while the CDK has IPv6 disabled. 

The launchpad-missioncontrol which uses WildFly and not Wildfly Swarm has this parameter set.

Setting this parameter will AFAIK have no effect on the CDK.
